### ISSUE TITLE
💻 [feature] front/pagination

### ISSUE THREAD

**Issue by dadaqq1009** [5g-FleaMarket/5g-fleamarket#146]
# 💻 기능 개요

프론트 
검색기능 연결과 페이지네이션 연결
### ✅ TODO

- [ ] 검색기능 헤더에 연결 
- [ ] 헤더 js 따로 분리
- [ ] 메인 페이지 상품목록 페이지네이션
- [ ] 검색목록 페이지네이션
