### ISSUE TITLE
💻 [feature] OAuth 회원가입 유저를 위한 API 추가

### ISSUE THREAD

**Issue by wth2052** [5g-FleaMarket/5g-fleamarket#54]
# 💻 기능 개요

 OAuth 회원가입 유저를 위한 API 추가를 하게 되었습니다.
처음엔 이름까지 받아오고 있었지만 이 민감정보를 유저 개인에게 맡겨 프론트에서 입력하게 함으로써
민감 정보에 대한 이슈를 해결할 수 있습니다.
### ✅ TODO

- [x] OAuthDTO Extend하여 DTO 생성
- [x] API 주소 API 명세서에 업데이트하기
- [x] API 로직 제작
- [x] 푸시하여 이슈 닫기
